export const FETCHING_SETS = 'FETCHING_SETS';
export const FETCHED_SETS = 'FETCHED_SETS';
export const FETCHED_SETS_ERROR = 'FETCHED_SETS_ERROR';

export const ADDING_SET = 'ADDING_SET';
export const ADDED_SET = 'ADDED_SET';
export const ADDED_SET_ERROR = 'ADDED_SET_ERROR';

export const REMOVING_SET = 'REMOVING_SET';
export const REMOVED_SET = 'REMOVED_SET';
export const REMOVED_SET_ERROR = 'REMOVED_SET_ERROR';

export const UPDATING_SET = 'UPDATING_SET';
export const UPDATED_SET = 'UPDATED_SET';
export const UPDATED_SET_ERROR = 'UPDATED_SET_ERROR';