/* SET CONSTANTS */
export const FETCHING_SET = 'FETCHING_SET';
export const FETCHED_SET = 'FETCHED_SET';
export const FETCHED_SET_ERROR = 'FETCHED_SET_ERROR';
export const ADDING_CARDSTOSET = 'ADDING_CARDSTOSET';
export const ADDED_CARDSTOSET = 'ADDED_CARDSTOSET';
export const ADDED_CARDSTOSET_ERROR = 'ADDED_CARDSTOSET_ERROR';
export const REMOVING_CARDSFROMSET = 'REMOVING_CARDSFROMSET';
export const REMOVED_CARDSFROMSET = 'REMOVED_CARDSFROMSET';
export const REMOVED_CARDSFROMSET_ERROR = 'REMOVED_CARDSFROMSET_ERROR';