export const FETCHING_COURSE = 'FETCHING_COURSE';
export const FETCHED_COURSE = 'FETCHED_COURSE';
export const FETCHED_COURSE_ERROR = 'FETCHED_COURSE_ERROR';

export const ADDING_STUDENT = 'ADDDING_STUDENT';
export const ADDED_STUDENT = 'ADDED_STUDENT';
export const ADDED_STUDENT_ERROR = 'ADDED_STUDENT_ERROR';

export const REMOVING_STUDENT = 'REMOVING_STUDENT';
export const REMOVED_STUDENT = 'REMOVED_STUDENT';
export const REMOVED_STUDENT_ERROR = 'REMOVED_STUDENT_ERROR';

export const ADDING_SET = 'ADDDING_SET';
export const ADDED_SET = 'ADDED_SET';
export const ADDED_SET_ERROR = 'ADDED_SET_ERROR';

export const REMOVING_SET = 'REMOVING_SET';
export const REMOVED_SET = 'REMOVED_SET';
export const REMOVED_SET_ERROR = 'REMOVED_SET_ERROR';

