export const FETCHING_PROFILE = 'FETCHING_PROFILE';
export const FETCHED_PROFILE = 'FETCHED_PROFILE';
export const FETCHED_PROFILE_ERROR = 'FETCHED_PROFILE_ERROR';
export const UPDATING_IMAGE = 'UPDATING_IMAGE';
export const UPDATED_IMAGE = 'UPDATED_IMAGE';
export const UPDATED_IMAGE_ERROR = 'UPDATED_IMAGE_ERROR';