export const FETCHING_TEACHERSETS = 'FETCHING_TEACHERSETS';
export const FETCHED_TEACHERSETS = 'FETCHED_TEACHERSETS';
export const FETCHED_TEACHERSETS_ERROR = 'FETCHED_TEACHERSETS_ERROR';

export const FETCHING_TEACHERSET = 'FETCHING_TEACHERSET';
export const FETCHED_TEACHERSET = 'FETCHED_TEACHERSET';
export const FETCHED_TEACHERSET_ERROR = 'FETCHED_TEACHERSET_ERROR';
export const ADDING_TEACHERSET = 'ADDING_TEACHERSET';
export const ADDED_TEACHERSET = 'ADDED_TEACHERSET';
export const ADDED_TEACHERSET_ERROR = 'ADDED_TEACHERSET_ERROR';
export const REMOVING_TEACHERSET = 'REMOVING_TEACHERSET';
export const REMOVED_TEACHERSET = 'REMOVED_TEACHERSET';
export const UPDATING_TEACHERSET = 'UPDATING_TEACHERSET';
export const UPDATED_TEACHERSET = 'UPDATED_TEACHERSET';

export const ADDING_CARDSTOSET = 'ADDING_CARDSTOSET';
export const ADDED_CARDSTOSET = 'ADDED_CARDSTOSET';
export const REMOVING_CARDSFROMSET = 'REMOVING_CARDSFROMSET';
export const REMOVED_CARDSFROMSET = 'REMOVED_CARDSFROMSET';

